---
## Create Templates for the Routers ##
- name: Generate Configuration for all routers
  gather_facts: no
  connection: local
  hosts: all
  tags: [ template ]
  tasks:
    - include_vars: "input_router.yml"
    - name: create the directory for the configuration
      file: path=router_config  state=directory
      run_once: true
    - name: Generate Configuration
      template: src={{dev_os}}/augment_template.j2 dest=router_config/{{inventory_hostname}}-{{ nodes[inventory_hostname].jira }}-{{ nodes[inventory_hostname].path }}-router-config.txt
